### ISSUE TITLE
Hi! Tkinter problem

### ISSUE THREAD

**Issue by tedvr** [qppddb/Cymatics-Generator#1]

**Comment by tedvr** [comment]
Hi! Looks like awesome work! But when I try to run your file, the GUI appears then when I set a frequency and hit 'Generate' i get the following message:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\tedvr\PycharmProjects\Cymatics\Cymatics-Generator\Cymatics-With-GUI.py", line 105, in generate
    os.makedirs(path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: ''
